storage:
  data_dir: "./data"
  max_chunk_size: 512
  min_chunk_size: 100

chunking:
  overlap_tokens: 50
  semantic_threshold: 0.75
  code_languages:
    - rust
    - python
    - javascript
    - typescript
    - java
    - cpp
    - c
    - go

embedding:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  dimension: 384
  batch_size: 32

mcp:
  transport: "stdio"  # Uses stdin/stdout instead of network

graph:
  max_connections: 10
  similarity_threshold: 0.7